version: 0.2
phases:
    install:
        commands:
            # installation commands
    pre_build:
        commands:
            #- echo Restore started on `date`
            #- dotnet restore ClassroomApp.csproj
            - echo Logging in to Amazon ECR...
            - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
            - REPOSITORY_URI=852659409621.dkr.ecr.us-east-1.amazonaws.com/ecr_sample_sre
            - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
            - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
    build:
        commands:
            - echo Build started on `date`
            - dotnet publish -c release -o ./build_output ClassroomApp.csproj
            - echo Building the Docker image...          
            - docker build -t $REPOSITORY_URI:latest .
            - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG 
    post_build:
        commands:
            - echo Build completed on `date`
            - echo Pushing the Docker image...
            - docker push $REPOSITORY_URI:latest
            - docker push $REPOSITORY_URI:$IMAGE_TAG
            - echo Writing image definitions file...
            - printf '[{"name":"ClassroomApp","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
            - cat imagedefinitions.json 
artifacts:
  files:
    - CodeBuild-ClassroomApp/build_output/**/*
    - imagedefinitions.json
    #- scripts/**/*
    #- appspec.yml