version: 0.2
phases:
    install:
        commands:
            # installation commands
    pre_build:
        commands:
            #- echo Restore started on `date`
            #- dotnet restore ClassroomApp.csproj
            - echo Logging in to Amazon ECR...
            - aws --version
            - aws ecr get-login-password --region $AWS_DEFAULT_REGION
            - REPOSITORY_URI=852659409621.dkr.ecr.us-east-1.amazonaws.com/ecr_sample_sre
            - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
            - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
            - dotnet tool install --global dotnet-sonarscanner
    build:
        commands:
            - echo Build started on `date`
            - dotnet sonarscanner begin /k:"SRE-Demo" /d:sonar.host.url="http://54.173.241.254:9000"  /d:sonar.login="sqp_9678b170967e40091d3e70d5361d9d79b453352e"
            - dotnet build
            - dotnet sonarscanner end /d:sonar.login="sqp_9678b170967e40091d3e70d5361d9d79b453352e"
            - dotnet restore
            - dotnet build --no-restore
            - dotnet publish --no-restore --output build_output
            # - dotnet publish -c release -o ./build_output ClassroomApp.csproj
            # - echo Building the Docker image...          
            # - docker build -t $REPOSITORY_URI:latest .
            # - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG 
    post_build:
        commands:
            - echo Build completed on `date`
            # - echo Pushing the Docker image...
            # - docker push $REPOSITORY_URI:latest
            # - docker push $REPOSITORY_URI:$IMAGE_TAG
            # - echo Writing image definitions file...
            # - printf '[{"name":"ClassroomApp","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
            # - cat imagedefinitions.json 
artifacts:
  files:
    base-directory: build_output
    files:
      - '**/*'
    #- ./build_output/**/*
    #- imagedefinitions.json
    #- scripts/**/*
    #- appspec.yml