# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  classroomapp:
    image: classroomapp
    build:
      context: .
      dockerfile: src/Dockerfile
    ports:
      - 5003:5003
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
