apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    kubernetes.io/ingress.class: alb
  labels:
    app: sre-demo
  name: sre-demo
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: sre-demo
          servicePort: 8080
        path: /*
# apiVersion: v1
# kind: Service
# metadata:
#   name: sre-demo
#   labels:
#     app: sre-demo
# spec:
#   selector:
#     app: sre-demo
#   type: LoadBalancer
#   ports: 
#     - protocol: TCP
#       port: 8080
#       targetPort: 8080