apiVersion: v1
kind: Service
metadata:
  name: sre-demo-service
  labels:
    app: sre-demo
spec:
  selector:
    app: sre-demo
  type: LoadBalancer
  ports: 
    - protocol: TCP
      port: 80
      targetPort: 80